language: 
    python
python:
    - 2.6
    - 2.7
    - pypy
install:
    - pip install -r requirements.txt
    - pip install .
    - pip install pytest
    - pip install coveralls
    - pip install nose
script: 
    - python setup.py install
    - nosetests --with-coverage 
after_success:
    - coveralls --verbose
notifications:
    email:
        - parth.kolekar@students.iiit.ac.in
